<!DOCTYPE html>
<html>
<head>
  <style>
    .triangle {
      width: 0;
      height: 0;
      border-left: 50px solid transparent;
      border-right: 50px solid transparent;
      border-bottom: 100px solid red;
      position: absolute;
      margin: 20px;
    }

    .explosion {
      width: 100px;
      height: 100px;
      border-radius: 50%;
      background-color: yellow;
      position: absolute;
      left: -25px;
      top: -50px;
      animation: explosion 0.5s ease-out;
    }

    @keyframes explosion {
      0% {
        transform: scale(0);
      }
      100% {
        transform: scale(1);
      }
    }

    #score {
      position: absolute;
      top: 0;
      right: 0;
      padding: 10px;
      font-size: 20px;
    }
  </style>
</head>
<body>
  <div id="score">Points: 0</div>
  <div class="triangle" onclick="explode(this)"></div>
  <div class="triangle" onclick="explode(this)"></div>
  <div class="triangle" onclick="explode(this)"></div>
  <div class="triangle" onclick="explode(this)"></div>
  <div class="triangle" onclick="explode(this)"></div>
  
  <script>
    let score = 0;
    const scoreCounter = document.getElementById("score");
    const triangles = document.querySelectorAll(".triangle");
    
    triangles.forEach(function(triangle) {
      randomizeTrianglePosition(triangle);
    });
    
    function explode(triangle) {
      let x = triangle.offsetLeft;
      let y = triangle.offsetTop;
      let explosion = document.createElement("div");
      explosion.classList.add("explosion");
      explosion.style.left = x - 25 + "px";
      explosion.style.top = y - 50 + "px";
      document.body.appendChild(explosion);
      triangle.style.visibility = "hidden";
      setTimeout(() => {
        randomizeTrianglePosition(triangle);
        triangle.style.visibility = "visible";
        explosion.remove();
      }, 500);
      score++;
      scoreCounter.innerHTML = `Points: ${score}`;
    }

    function randomizeTrianglePosition(triangle) {
      let x = Math.floor(Math.random() * window.innerWidth);
      let y = Math.floor(Math.random() * window.innerHeight);
      triangle.style.left = x + "px";
      triangle.style.top = y + "px";
    }
  </script>
</body>
</html>

